export enum UserProc{
    DO_USER = 'DO_USER',
    ARRAY_BOOKS = 'ARRAY_BOOKS',
    START_ADD_BOOK_TO_CART = 'START_ADD_BOOK_TO_CART',
    SELECT_BOOK = 'SELECT_BOOK',
    CHOOSED_BOOK = 'CHOOSED_BOOK',
    ADD_BOOK = 'ADD_BOOK',
    ADD_BOOK_TO_CART = 'ADD_BOOK_TO_CART'
}