export enum AdminBooksProc{
    DO_SAVE_BOOK = 'DO_SAVE_BOOK',
    OPEN_MODAL_ADD_BOOKS = 'OPEN_MODAL_ADD_BOOKS',
    CLOSE_MODAL_ADD_BOOKS = 'CLOSE_MODAL_ADD_BOOKS',
    APDATE_ARRAY_BOOKS = 'APDATE_ARRAY_BOOKS',
    DO_EDIT_BOOK = 'DO_EDIT_BOOK',
    CHECK_EDIT_BOOK = 'CHECK_EDIT_BOOK',
    DO_SAVE_EDIT_BOOK = 'DO_SAVE_EDIT_BOOK',
    CHECK_DELET_BOOKS = 'CHECK_DELET_BOOKS',
    DO_DELETE_BOOKS = 'DO_DELETE_BOOKS'
}